name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build TypeScript source files
              run: yarn build

            - name: Run tests
              run: yarn test
              env:
                  CI: true
